---

- name: Create User www-data
  user:
    name: 'www-data'
    group: 'www-data'
    shell: '/bin/false'
    system: yes
    createhome: no


- name: Install lighttpd Webserver 
  apt:
    pkg: 'lighttpd'
    state: 'latest'
    update_cache: yes
    cache_valid_time: 86400


- name: Create openssl dhparam if they don't exist at /etc/ssl/certs/dhparam.pem.
  command: '/usr/bin/openssl dhparam -out /etc/ssl/certs/dhparam.pem 4096'
  args:
    creates: /etc/ssl/certs/dhparam.pem
  notify: lighttpd restart


- name: Create /etc/lighttpd/lighttpd.conf
  template:
    src: 'templates/lighttpd/lighttpd.conf'
    dest: '/etc/lighttpd/lighttpd.conf'
    owner: root
    group: root
    mode: 0644
  notify: lighttpd restart
