---

- name: Install FFNodeList dependencies
  apt:
    pkg: '{{ item }}'
    state: 'latest'
    update_cache: yes
    cache_valid_time: 86400
  with_items:
    - perl
    - cpanminus
    - libjson-pp-perl
    - libwww-perl

- name: Create '/var/www/HOSTNAME/FFNodeList' directory
  file:
    path: '/var/www/{{ hostname }}/FFNodeList'
    state: directory
    mode: 'u=rwx,g=rx,o=rx'

- name: FFNodeList Template
  template:
    src: 'templates/FFNodeList/generateList.pl'
    dest: '/opt/freifunk/genNodeList.pl'
    mode: '0755'

- name: FFNodeList JavaScript
  copy:
    src: 'templates/FFNodeList/sortableTables.js'
    dest: '/var/www/{{ hostname }}/FFNodeList/sortableTables.js'
    owner: 'www-data'
    group: 'www-data'
    mode: '0755'

- name: Install Perl modules
  cpanm:
    name: '{{ item }}'
  with_items:
    - 'HTML::Entities'
    - 'LWP::Simple'
    - 'utf8'
    - 'JSON'
