---

- name: Install FFNodeList dependencies
  apt:
    name: '{{ packages }}'
    state: 'latest'
    update_cache: yes
    cache_valid_time: 86400
  vars:
    packages:
    - perl
    - cpanminus
    - libjson-pp-perl
    - libwww-perl
  when: nodelist

- name: Create '/var/www/HOSTNAME/FFNodeList' directory
  file:
    path: '/var/www/{{ hostname }}/FFNodeList'
    state: directory
    mode: 'u=rwx,g=rx,o=rx'
  when: nodelist

- name: FFNodeList Template
  template:
    src: 'templates/FFNodeList/generateList.pl'
    dest: '/opt/freifunk/genNodeList.pl'
    mode: '0755'
  when: nodelist

- name: FFNodeList JavaScript
  copy:
    src: 'templates/FFNodeList/sortableTables.js'
    dest: '/var/www/{{ hostname }}/FFNodeList/sortableTables.js'
    owner: 'www-data'
    group: 'www-data'
    mode: '0755'
  when: nodelist

- name: Install Perl modules
  cpanm:
    name: '{{ item }}'
  with_items:
    - 'HTML::Entities'
    - 'LWP::Simple'
    - 'utf8'
    - 'JSON'
  when: nodelist


- name: Add cron job for FFNodeList script
  cron:
    name: 'gen FFNodeList'
    job: '/opt/freifunk/genNodeList.pl > /dev/null'
    minute: '*/5'
    user: 'root'
    state: 'present'
    cron_file: '/etc/crontab'


