---

- name: Update packages and users on all nodes
  hosts: freifunk
  tags: 
  - base
  - users
  - home
  - base-packages
  - ssh_authorized_keys
  - home_environment
  - new-user
  roles:
    - base-packages
    - ssh_authorized_keys
    - sshd
    - home_environment

- name: Configure basic network setup for gw01.ffbsee.net
  hosts: gw01.ffbsee.net
  tags:
  - network
  - interfaces
  roles:
    - network
  
- name: Configure freifunk network setup for gw01.ffbsee.net
  hosts: gw01.ffbsee.net
  tags:
  - backbone
  - fastd
  - freifunk-backbone
  - freifunk-update-script
  - fastd-install
  - fastd-config
  roles:
#    - freifunk-backbone
#    - freifunk-update-script
#    - fastd-install
#    - fastd-config

- name: Configure network routing for gw01.ffbsee.net
  hosts: gw01.ffbsee.net
  tags: 
  - routing
  roles:
#    - firewall
#    #- dhcpd
#    - dhcp-relay
#    - unbound
#    - freifunk-icvpn
#    - bird
#    - tinc

- name: Configure web setup for gw01.ffbsee.net
  hosts: gw01.ffbsee.net
  tags: web
  roles:
    #- nginx
    #- gateway-page
#    - freifunk-karte-json
#    - FFNodeList
