---

- name: Install common packages for gw01.ffbsee.net
  hosts: gw01.ffbsee.net
  tags: base
  roles:
    - base-packages
    - ssh_authorized_keys
    - home_environment

- name: Configure network setup for gw01.ffbsee.net
  hosts: gw01.ffbsee.net
  tags: network
  roles:
    - network
    - freifunk-backbone
    - freifunk-update-script
    - fastd-install
    - fastd-config

- name: Configure network routing for gw01.ffbsee.net
  hosts: gw01.ffbsee.net
  tags: routing
  roles:
    - firewall
    #- dhcpd
    - dhcp-relay
    - unbound
    #- freifunk-icvpn
    #- bird

- name: Configure web setup for gw01.ffbsee.net
  hosts: gw01.ffbsee.net
  tags: web
  roles:
    #- nginx
    #- gateway-page
    - freifunk-karte-json
    - FFNodeList
