---

- name: Install common packages for gw02.ffbsee.net
  hosts: gw02.ffbsee.net
  tags: 
  - base
  - users
  - home
  - base-packages
  - base-packages
  - ssh_authorized_keys
  - ssh_authorized_keys
  - home_environment
  - home_environment
  - new-user
  roles:
    - base-packages
    - ssh_authorized_keys
    - sshd
    - home_environment

- name: Update packages and users on all nodes
  hosts: freifunk
  tags:
  - home_environment
  - motd
  roles:
    - home_environment
    - motd
    
- name: Configure basic network setup for gw02.ffbsee.net
  hosts: gw02.ffbsee.net
  tags:
  - network
  - interfaces
  roles:
    - network

- name: Configure freifunk network setup for gw02.ffbsee.net
  hosts: gw02.ffbsee.net
  tags:
  - backbone
  - fastd
  - freifunk-backbone
  - freifunk-update-script
  - fastd-install
  - fastd-config
  roles:
    - freifunk-backbone
    - freifunk-update-script
    - fastd-install
    - fastd-config

- name: Configure network routing for gw02.ffbsee.net
  hosts: gw02.ffbsee.net
  tags:
  - routing
  - iptables
  - ip6tables
  - firewall
  roles:
    - firewall  

- name: Configure ovh dns script for gw02.ffbsee.net
  hosts: gw02.ffbsee.net
  tags: ovh
  roles:
    - ovh-dns-update

- name: Confiure network routing for gw02.ffbsee.net
  hosts: gw02.ffbsee.net
  tags:
  - routing
  - dhcp
  - dhcpd
  - isc-dhcp
  - isc
  - isc-dhcp-server
  - isc-dhcp-relay
  - dhcp-relay
  roles:
    - dhcp-relay

- name: Configure network routing for gw02.ffbsee.net
  hosts: gw02.ffbsee.net
  tags:
  - dns
  - unbound
  - role-unbound
  - bind
  roles:
    - unbound
    - unbound_freifunk_tlds
    - bird

- name: Configure web setup for gw02.ffbsee.net
  hosts: gw02.ffbsee.net
  tags: web
  roles:
    - nginx
    - gateway-page
#   - freifunk-karte-json
#   - FFNodeList
