---

- name: Install common packages
  hosts: io.rack.ccczh.ch
  roles:
    - base-packages # Grundsystem installieren
    - ssh_authorized_keys # Admin User
    - home_enviroment # vimrc
    - network # interface
    - freifunk-backbone # FFBSee-Backbone
    - freifunk-update-script # FFBSee-Start-Script
    - fastd-install # FastD
    - fastd-config  # FastD
    - firewall # Firewall
    - dhcpd # DHCP
    - nginx # Webserver
    - gateway-page 
    - unbound # Recursive DNS Resolver
    - freifunk-icvpn # Resolve Freifunk TLDs
    - FFNodeList
    - bird
