---
- name: check if ansible is not to old
  hosts: localhost
  tags:
   - default
  roles:
    - ansible_version
  gather_facts: no

- name: Update packages and users on all nodes
  hosts: map.ffbsee.net 
  tags: 
  - base
  - users
  - home
  - base-packages
  - base_packages
  - ssh_authorized_keys
  - home_environment
  - new-user
  - base
  - ssh
  - sshd
  - ssh_authorized_keys
  - auth
  roles:
    - base_packages
    - manage_users
    - ssh_authorized_keys
    - sshd
    - home_environment

- name: Update packages and users on all nodes
  hosts: map.ffbsee.net
  tags: 
  - home_environment
  - motd
  roles:
    - home_environment
    - motd
    - install-bat

- name: Configure basic network setup for map.ffbsee.net
  hosts: map.ffbsee.net
  tags:
  - network
  - interfaces
  roles:
    - network
  
- name: Configure freifunk network setup for map.ffbsee.net
  hosts: map.ffbsee.net
  tags:
  - backbone
  - fastd
  - freifunk-backbone
  - freifunk-update-script
  - fastd-install
  - fastd-config
  roles:
    - freifunk-backbone
    - freifunk-update-script
    - fastd-install
    - fastd-config

- name: Configure network routing for map.ffbsee.net
  hosts: map.ffbsee.net
  tags: 
  - routing
  - iptables
  - ip6tables
  - firewall
  roles:
   - firewall
   - bird

- name: Configure network routing for map.ffbsee.net
  hosts: map.ffbsee.net
  tags:
  - routing
  - dhcp
  - dhcpd
  - isc-dhcp
  - isc
  - isc-dhcp-server
  - isc-dhcp-relay
  - dhcp-relay
  roles:
  - dhcpd

- name: Configure web setup for map.ffbsee.net
  hosts: map.ffbsee.net
  tags: web
  roles:
   - nginx
   - gateway-page
#    - freifunk-karte-json
#    - FFNodeList

- name: install telegraf
  hosts: map.ffbsee.net
  become: yes
  tags:
    - telegraf
  roles:
    - telegraf

- name: install prometheus
  hosts: map.ffbsee.net
  tags:
    - prometheus
  roles:
    - prometheus

- name: install grafana
  hosts: map.ffbsee.net
  tags:
    - grafana
  roles:
    - grafana
  tasks:
    - name: install dashboards
      copy:
        src: "files/grafana_dashboards/{{ item }}"
        dest: "{{ grafana_dashboard_dir }}/{{ item }}"
        mode: '0644'
        remote_src: yes
  loop:
    - freifunk_overview.json
    - freifunk_router_detail.json

- name: install golang
  hosts: map.ffbsee.net
  roles:
     - role: golang

- name: install xperimental/freifunk-exporter
  hosts: map.ffbsee.net
  tasks:
    - name: clone repository
      git:
        repo: 'https://github.com/xperimental/freifunk-exporter.git'
        dest: "{{ freifunk_exporter_path }}"
    - name: Build the default target
      make:
        chdir: "{{ freifunk_exporter_path }}"
    - name: install freifunk-exporter service
      copy:
        content: |
          [Unit]
          Description=freifunk-exporter

          [Service]
          Type=simple
          ExecStart=freifunk-exporter --cache-interval 30s --source-url https://meta.ffbsee.net/data/meshviewer.json

          [Install]
          WantedBy=multi-user.target
        dest: /lib/systemd/system/freifunk-exporter.service
    - name: enable and start freifunk-exporter
      systemd:
        state: started
        enabled: yes
        name: freifunk-exporter
  vars:
    freifunk_exporter_path: /opt/freifunk-exporter
    #defaults to port: 9295
