---

- name: Install common packages
  hosts: meta.ffbsee.net
  roles:
    - base-packages # Grundsystem installieren
    - ssh_authorized_keys # Admin User
    - home_enviroment # vimrc
    - network # interface
    - freifunk-backbone # FFBSee-Backbone
    - freifunk-update-script # FFBSee-Start-Script
    - fastd-install # FastD
    - fastd-config  # FastD
    - nginx # Webserver
