---

- name: Update admin user accounts
  hosts: all
  tags:
   - ssh
   - access
   - default
  roles:
    - ssh_authorized_keys
    - sshd

- name: Update Packages
  hosts: all
  tags:
   - update
  roles:
    - base_packages
    - home_environment

