---
- name: check if ansible is not to old
  hosts: localhost
  tags:
   - default
  roles:
    - ansible_version
  gather_facts: no

- name: Update admin user accounts
  hosts: all
  tags:
   - ssh
   - access
   - default
  roles:
    - manage_users
    - ssh_authorized_keys
    - sshd

- name: Update Packages
  hosts: all
  tags:
   - update
  roles:
    - base_packages
    - home_environment

