---
- name: save iptables
  command: iptables-save
  become: true

#  - name: save iptables
#    iptables:  # this is the new stuff
#      path: /etc/sysconfig/iptables
#      state: save
#      backup: true  # should function similarly to lineinfile, appending datetime stamp to filename
#    notify: reload iptables

- name: reload iptables
  iptables: # this is the new stuff
    state: reload
