---
- name: fastd_secret_key_defined
  set_fact:
    fastd_secret_key_set: "{{ lookup('vars', 'fastd_secret_key_var' + key_postfix, default='') == '' }}"

- name: Generate fastd secret key
  shell: "fastd --generate-key --machine-readable > /etc/fastd/secret{{ key_postfix }}.txt;"
  args:
    creates: "/etc/fastd/secret{{ key_postfix }}.txt"
  when: fastd_secret_key_set | bool

- name: Retrieve fastd secret key
  slurp:
    src: "/etc/fastd/secret{{ key_postfix }}.txt"
  register: fastd_secret_key_data
  when: fastd_secret_key_set | bool

- name: Read in fastd secret key
  set_fact:
    "fastd_secret_key{{ key_postfix }}": "{{ fastd_secret_key_data['content'] | b64decode | trim }}"
    fastd_secret_key: "{{ fastd_secret_key_data['content'] | b64decode | trim }}"
  when: fastd_secret_key_set | bool

- name: Put secret key to host
  template:
    src: "templates/secret_key.txt"
    dest: "/etc/fastd/secret_key{{ key_postfix }}.txt"
    owner: 'nobody'
    group: 'root'
    mode: 'u=rw,g=r,o=r'

- name: Create fastd public key
  shell: "fastd --config /etc/fastd/secret_key{{ key_postfix }}.txt --show-key --machine-readable > /etc/fastd/public_key{{ key_postfix }}.txt;"
  args:
    creates: "/etc/fastd/public_key{{ key_postfix }}.txt"

- name: Retrieve fastd public key
  slurp:
    src: "/etc/fastd/public_key{{ key_postfix }}.txt"
  register: fastd_public_key_data

- name: Read in fastd public key
  set_fact:
    "fastd_public_key{{ key_postfix }}": "{{ fastd_public_key_data['content'] | b64decode | trim }}"
    fastd_public_key: "{{ fastd_public_key_data['content'] | b64decode | trim }}"
