---
- name: Create user nobody for fastd
  user:
    name: nobody
    shell: '/bin/false'
    createhome: no

- name: Create fastd directory
  file:
    path: '/etc/fastd'
    state: directory
    mode: 'u=rwx,g=rx,o=rx'

- name: Create 'fastd/peers' directory
  file:
    path: '/etc/fastd/peers'
    state: directory
    mode: 'u=rwx,g=rx,o=rx'

- name: Copy fastd blacklisting scipt
  template:
    src: 'templates/fastd/fastd-blacklist.sh'
    dest: '/etc/fastd/fastd-blacklist.sh'
    owner: nobody
    group: root
    mode: 'u=rwx,g=rx,o=rx'

- name: Copy fastd blacklist json file
  template:
    src: 'templates/fastd/fastd-blacklist.json'
    dest: '/etc/fastd/fastd-blacklist.json'
    owner: nobody
    group: root
    mode: 'u=rwx,g=rx,o=rx'

- import_tasks: key.yml
- import_tasks: backbone.yml
- import_tasks: node.yml
