---
- name: Copy motd.sh to gateway
  template:
    src: 'files/motd.sh'
    dest: '/etc/motd.sh'
    owner: 'root'
    group: 'admins'
    mode: 'u=rwx,g=rx,o='
  register: motdsh

- name: Set fancy motd
  command: '/etc/motd.sh {{ hostname }}'
  when: motdsh.changed

