---

- name: Install bird 
  apt:
    name: 'bird'
    state: present
    update_cache: yes
    cache_valid_time: 86400


- name: Copy bird and bird6 config for this specific gateway
  copy:
    src: 'files/bird/bird_{{ hostname }}/'
    dest: '/etc/bird'
    owner: 'root'
    group: 'root'
    mode: '0755'

