---

- name: Create www-data user
  user:
    name: 'www-data'
    group: 'www-data'
    shell: '/bin/false'
    system: yes
    createhome: no

- name: Create /var/www directory
  file:
    path: '/var/www'
    state: directory
    mode: 'u=rwx,g=rx,o=rx'

- name: Copy /var/www/status_page_style.css
  copy:
    src: 'files/www/status_page_style.css'
    dest: '/var/www/status_page_style.css'
    owner: 'www-data'
    group: 'www-data'
    mode: 'u=rw,g=r,o=r'

- name: Copy /var/www/status_page_background.png
  copy:
    src: 'files/www/status_page_background.png'
    dest: '/var/www/status_page_background.png'
    owner: 'www-data'
    group: 'www-data'
    mode: 'u=rw,g=r,o=r'

- name: Copy /var/www/counter.svg
  copy:
    src: 'files/www/counter.svg'
    dest: '/var/www/counter.svg'
    owner: 'www-data'
    group: 'www-data'
    mode: 'u=rw,g=r,o=r'

- name: Put hostname in JSON file
  template:
    src: 'templates/www/cgi-bin/data'
    dest: '/var/www/cgi-bin/data'
    owner: 'www-data'
    group: 'www-data'
    mode: 'u=rw,g=r,o=r'
