---

- name: Copy network interface configuration file and restart networking
  copy:
    src: 'roles/network/files/interfaces_{{ hostname }}.conf'
    dest: '/etc/network/interfaces'
  notify: restart networking

