---

- name: Install ferm
  apt:
    pkg: '{{ item }}'
    state: 'latest'
    update_cache: yes
    cache_valid_time: 86400
  with_items:
    - ferm

- name: copy ferm config
  template:
    src: files/ferm.conf
    dest: /etc/ferm/ferm.conf
    owner: root
    group: root
    mode: 0644 
   
