---

- name: Install ferm
  apt:
    pkg: 'ferm'
    state: 'latest'
    update_cache: yes
    cache_valid_time: 86400

- name: Copy ferm configuration
  template:
    src: 'templates/ferm.conf'
    dest: '/etc/ferm/ferm.conf'
    owner: root
    group: root
    mode: 'u=rw,g=r,o=r'
  notify: restart ferm
