---

- name: iptables installieren
  apt:
    pkg: 'iptables'
    state: 'latest'
    update_cache: yes
    cache_valid_time: 86400

- name: Reject RFC 1918 addresses
  become: true
  iptables:
    chain: FORWARD
    destination: 192.168.0.0/16
    jump: REJECT
    reject_with: icmp-net-prohibited
    state: present
    ip_version: ipv4
  notify: save ip4tables
  when: block_rfc1918_traffic

- name: Reject RFC 1918 addresses
  become: true
  iptables:
    chain: FORWARD
    destination: 172.16.0.0/12
    out_interface: "{{ block_rfc1918_interface }}"
    jump: REJECT
    reject_with: icmp-net-prohibited
    state: present
    ip_version: ipv4
  notify: save ip4tables
  when: block_rfc1918_traffic

- name: Reject RFC 1918 addresses
  become: true
  iptables:
    chain: FORWARD
    destination: 10.0.0.0/8
    out_interface: "{{ block_rfc1918_interface }}"
    jump: REJECT
    reject_with: icmp-net-prohibited
    state: present
    ip_version: ipv4
  notify: save ip4tables
  when: block_rfc1918_traffic

- name: Reject APIPA - link-local addresses
  become: true
  iptables:
    chain: FORWARD
    destination: 169.254.0.0/16
    jump: REJECT
    reject_with: icmp-net-prohibited
    state: present
    ip_version: ipv4
  notify: save ip4tables

- name: Reject ISP - carrier-grade NAT addresses
  become: true
  iptables:
    chain: FORWARD
    destination: 100.64.0.0/10
    jump: REJECT
    reject_with: icmp-net-prohibited
    state: present
    ip_version: ipv4
  notify: save ip4tables

- name: Reject multicast addresses
  become: true
  iptables:
    chain: FORWARD
    destination: 224.0.0.0/3
    jump: REJECT
    reject_with: icmp-net-prohibited
    state: present
    ip_version: ipv4
  notify: save ip4tables

- name: Reject IANA IPv4 Special Purpose Address Registry addresses
  become: true
  iptables:
    chain: FORWARD
    destination: 192.0.0.0/24
    jump: REJECT
    reject_with: icmp-net-prohibited
    state: present
    ip_version: ipv4
  notify: save ip4tables

- name: Reject TEST-NET-1 addresses
  become: true
  iptables:
    chain: FORWARD
    destination: 192.0.2.0/24
    jump: REJECT
    reject_with: icmp-net-prohibited
    state: present
    ip_version: ipv4
  notify: save ip4tables

- name: Reject 6to4 anycast relays (deprecated) addresses
  become: true
  iptables:
    chain: FORWARD
    destination: 192.88.99.0/24
    jump: REJECT
    reject_with: icmp-net-prohibited
    state: present
    ip_version: ipv4
  notify: save ip4tables

- name: Reject testing of inter-network communications addresses
  become: true
  iptables:
    chain: FORWARD
    destination: 198.18.0.0/15
    jump: REJECT
    reject_with: icmp-net-prohibited
    state: present
    ip_version: ipv4
  notify: save ip4tables

- name: Reject TEST-NET-2 addresses
  become: true
  iptables:
    chain: FORWARD
    destination: 198.51.100.0/24
    jump: REJECT
    reject_with: icmp-net-prohibited
    state: present
    ip_version: ipv4
  notify: save ip4tables

- name: Reject TEST-NET-3 addresses
  become: true
  iptables:
    chain: FORWARD
    destination: 203.0.113.0/24
    jump: REJECT
    reject_with: icmp-net-prohibited
    state: present
    ip_version: ipv4
  notify: save ip4tables


#
#
# NAT
# /sbin/iptables -t nat -A POSTROUTING -o {{ wan_interface }} -j MASQUERADE
#

- name: NAT vom 'WAN' Interface zum 'B.A.T.M.A.N.' Interface
  become: true
  iptables:
    table: nat
    chain: POSTROUTING
    out_interface: "{{ wan_interface }}"
    jump: MASQUERADE
    state: present
    ip_version: ipv4
  notify: save ip4tables

#/sbin/iptables -A FORWARD -i {{ wan_interface }} -o {{ ipv4_dhcp_interface }} -m state --state RELATED,ESTABLISHED -j ACCEPT
- name: NAT vom 'WAN' Interface zum 'B.A.T.M.A.N.' Interface
  become: true
  iptables:
    chain: FORWARD
    in_interface: "{{ wan_interface }}"
    out_interface: "{{ ipv4_dhcp_interface }}"
    jump: ACCEPT
    match: state
    ctstate: ESTABLISHED,RELATED
    state: present
    ip_version: ipv4
  notify: save ip4tables

#/sbin/iptables -A FORWARD -i {{ ipv4_dhcp_interface }} -o {{ wan_interface }} -j ACCEPT
- name: NAT vom 'WAN' Interface zum 'B.A.T.M.A.N.' Interface
  become: true
  iptables:
    chain: FORWARD
    in_interface: "{{ ipv4_dhcp_interface }}"
    out_interface: "{{ wan_interface }}"
    jump: ACCEPT
    state: present
    ip_version: ipv4
  notify: save ip4tables


# missing
# ICVPN Firewall Optionen, if required
#
#/sbin/iptables -A FORWARD -i {{ ipv4_dhcp_interface }} -o {{ icvpn_interface }} -j ACCEPT
#/sbin/iptables -A FORWARD -i {{ icvpn_interface }} -o {{ ipv4_dhcp_interface }} -j ACCEPT

#
# IPv6
#
# /sbin/ip6tables -A INPUT -i bat0 -p ipv6-icmp -m icmp6 --icmpv6-type 134 -j DROP
- name: icmpv6-type 134
  become: true
  iptables:
    chain: INPUT
    in_interface: "{{ ipv4_dhcp_interface }}"
    protocol: ipv6-icmp
    match: icmp6
    icmp_type: 134
    jump: DROP
    state: present
    ip_version: ipv6
  notify: save ip6tables

#/sbin/ip6tables -A FORWARD -m state --state RELATED,ESTABLISHED -j ACCEPT
- name: established_ipv6_traffic
  become: true
  iptables:
    chain: FORWARD
    match: state
    ctstate: ESTABLISHED,RELATED
    state: present
    ip_version: ipv6
    jump: ACCEPT
  notify: save ip6tables

#/sbin/ip6tables -A FORWARD -m state --state NEW -m connlimit --connlimit-above 200 --connlimit-mask 128 --connlimit-saddr -j DROP
- name: established_ipv6_traffic_complex
  become: true
  command: "ip6tables -A FORWARD -m state --state NEW -m connlimit --connlimit-above 200 --connlimit-mask 128 --connlimit-saddr -j DROP"

#/sbin/ip6tables -A FORWARD -i bat0 -o {{ wan_interface }} -j ACCEPT
- name: forward_ipv6_traffic
  become: true
  iptables:
    chain: FORWARD
    in_interface: "{{ ipv4_dhcp_interface }}"
    out_interface: "{{ wan_interface }}"
    state: present
    ip_version: ipv6
    jump: ACCEPT
  notify: save ip6tables

# #/sbin/ip6tables -A FORWARD -d fc00::/7 ! -o {{ wan_interface }} -j ACCEPT
- name: Block fc00::/7 to global_network 
  become: true
  iptables:
    chain: FORWARD
    destination: fc00::/7
    out_interface: "! {{ wan_interface }}"
    state: present
    ip_version: ipv6
    jump: ACCEPT
  notify: save ip6tables

#/sbin/ip6tables -A FORWARD -d fec0::/10 ! -o {{ wan_interface }} -j ACCEPT

- name: Block fec0::/1 to global_network 
  become: true
  iptables:
    chain: FORWARD
    destination: fec0::/1
    out_interface: "! {{ wan_interface }}"
    state: present
    ip_version: ipv6
    jump: ACCEPT
  notify: save ip6tables


#/sbin/ip6tables -A FORWARD -j DROP 
- name: Block undefined to global_network 
  become: true
  iptables:
    chain: FORWARD
    state: present
    jump: DROP
    ip_version: ipv6
  notify: save ip6tables

#/sbin/ip6tables -t nat -A POSTROUTING -o {{ wan_interface }} -j NETMAP --to {{ wan_ipv6_network }}

- name: NAT vom 'WAN' Interface zum 'B.A.T.M.A.N.' Interface
  become: true
  command: "ip6tables -t nat -A POSTROUTING -o {{ wan_interface }} -j NETMAP --to {{ wan_ipv6_network }}"


#{% if vpn_on_port_443 == 'true' %}#
#
# ICVPN Firewall Optionen
#
#/sbin/iptables -A FORWARD -i {{ ipv4_dhcp_interface }} -o {{ icvpn_interface }} -j ACCEPT
#/sbin/iptables -A FORWARD -i {{ icvpn_interface }} -o {{ ipv4_dhcp_interface }} -j ACCEPT

