---

- name: Install isc-dhcp-relay
  apt:
    name: 'isc-dhcp-relay'
    state: 'latest'
    update_cache: yes
    cache_valid_time: 86400
  when: freifunk_dhcp_relay

- name: Set DHCP Relay Servers Option
  debconf:
    name: 'isc-dhcp-relay'
    question: 'isc-dhcp-relay/servers'
    value: '{{ ipv4_dhcp_server }}'
    vtype: string
  notify: dpkg reconfigure isc-dhcp-relay
  when: freifunk_dhcp_relay

- name: set DHCP-Relay interface Option
  debconf:
    name: 'isc-dhcp-relay'
    question: 'isc-dhcp-relay/interfaces'
    value: '{{ ipv4_dhcp_interface }}'
    vtype: string
  notify: dpkg reconfigure isc-dhcp-relay
  when: freifunk_dhcp_relay

- name: Copy ISC DHCP Gateway config (backup)
  template:
    src: 'templates/dhcp/isc_dhcp_relay'
    dest: '/etc/default/isc-dhcp-relay'
    owner: 'root'
    group: 'root'
    mode: '0755'
  when: freifunk_dhcp_relay


