---

- name: create freifunk directory
  file:
    path: /opt/freifunk
    state: directory
    mode: 0755

- name: Get the MAC address
  set_fact:
    mac_address: "{{ hostvars[inventory_hostname]['ansible_' + wan_base_interface]['macaddress'] }}"

- name: copy freifunk update.sh template
  template: 
    src: 'templates/freifunk-files/update.sh'
    dest: '/opt/freifunk/update.sh'
    owner: root
    group: root
    mode: 'u=rwx,g=rx,o=rx'


