---

- name: Add debian.ch repo
  apt_repository:
    repo: '{{ item }}'
    state: 'present'
  with_items:
    - 'deb https://ftp.ch.debian.org/debian/ stretch main'
    - 'deb https://ftp.ch.debian.org/debian/ stretch-updates main'
    - 'deb https://ftp.ch.debian.org/debian/ stretch-backports main'

- name: Install Meshviewer apt packages
  apt:
    pkg: '{{ item }}'
    state: 'latest'
    update_cache: yes
    cache_valid_time: 86400
  with_items:
    - git
    - make
    - ruby-sass
    - apt-transport-https
    - node-grunt-legacy-util
    - node-grunt-legacy-log
    - node-findup-sync

- name: Add unstable apt repository for npm
  apt_repository:
    repo: deb https://ftp.ch.debian.org/debian/ sid main
    state: present

- name: Install npm from sid
  apt:
    pkg: 'npm'
    default_release: sid
    update_cache: yes
    cache_valid_time: 86400

- name: Install coffee-script
  npm:
    name: '{{ item }}'
    global: yes
  with_items: 
    - 'coffee-script'
    - 'js-yaml'
    - 'bower'

- name: Remove unstable apt repository for npm
  apt_repository:
    repo: deb https://ftp.ch.debian.org/debian/ sid main
    state: absent

- name: Clone meshviewer git
  git:
    repo: 'https://github.com/ffbsee/meshviewer.git'
    dest: '/tmp/meshviewer'
    clone: yes
    update: yes

- name: Install grunt-cli via npm
  npm:
    name: grunt-cli
    path: '/tmp/meshviewer'

- name: Run npm install
  command: npm install
  args:
    chdir: '/tmp/meshviewer'

- name: Execute Grunt
  shell: 'node_modules/.bin/grunt'
  args:
    chdir: '/tmp/meshviewer'

- name: Meshviewer nach /var/www/meshviewer kopieren
  # TODO: Clean this up
  shell: 'rm -rf /var/www/meshviewer && mv /tmp/meshviewer/build /var/www/meshviewer'

- name: Copy config file
  copy:
    src: 'files/meshviewer/config.json'
    dest: '/var/www/meshviewer/config.json'
    owner: www-data
    group: www-data
    mode: 'u=rw,g=r,o=r'
