---

- name: Install Meshviewer apt packages
  apt:
    pkg: '{{ item }}'
    state: 'latest'
    update_cache: yes
    cache_valid_time: 86400
  with_items:
    - git
    - make
    - ruby-sass

- name: unstable apt_repository for npm
  apt_repository:
    repo: deb https://ftp.ch.debian.org/debian/ sid main
    state: present

- name: Install npm from sid
  apt:
    pkg: 'npm'
    default_release: sid
    update_cache: yes
    cache_valid_time: 86400
 
- name: unstable apt_repository for npm
  apt_repository:
    repo: deb https://ftp.ch.debian.org/debian/ sid main
    state: absent


- name: Git clonen
  git:
    repo: 'https://github.com/ffbsee/meshviewer.git'
    dest: /tmp/meshviewer
    clone: yes
    update: yes

- name: grunt-cli via npm
  npm:
    name: grunt-cli
    path: /tmp/meshviewer


- name: npm install
  npm:
    path: /tmp/meshviewer

- name: execute Grunt
  shell: node_modules/.bin/grunt
  args:
    chdir: '/tmp/meshviewer'

- name: Meshviewer nach /var/www/meshviewer kopieren
  shell: 'rm -rf /var/www/meshviewer && mv /tmp/meshviewer/build /var/www/meshviewer'

- name: copy config file
  copy:
    src: files/meshviewer/config.json
    dest: /var/www/meshviewer/config.json
    owner: www-data
    group: www-data
    mode: 0644
