---
hostname: 'gw02.ffbsee.net'

ipv4_mesh_address: '10.15.224.2'

ipv6_suffix: ':2'
ipv6_radv_suffix: ':2'
ipv6_address: '{{ ipv6_prefix }}{{ ipv6_suffix }}'
mesh_ipv6_address: '{{ ipv6_address }}'
mesh_ipv6_extra_addr: ''
ipv6_radv_address: '{{ ipv6_prefix }}{{ ipv6_radv_suffix }}'
ipv6_radv_prefix: '{{ ipv6_prefix }}:/64'

wan_ipv6_network: '2a02:168:4638:f1::/64'
wan_ipv6_ip: '2a02:168:4638:f0::10'
wan_base_interface: 'enp1s0f0'
wan_vlan_id: '240'
wan_interface: '{{ wan_base_interface }}{% if wan_vlan_id != "" %}.{{ wan_vlan_id }}{% endif %}'
wan_ipv4_ip: '10.0.240.10' 

fastd_secret_key: ''
vpn_on_port_443: 'false'

run_mesh: 'true'
run_gateway: 'true'
run_webserver: 'true'
run_icvpn: 'false'
run_map: 'false'
run_stats: 'false'
freifunk_dhcp_relay: 'true'
da_laueft_ein_dhcp_relay: 'true'

fastd_peer_limit: ''
fastd_vpn_backbone_configs:
  - gw04
  - gw01

ipv6_uplink_announcen: 'true'
radv_AdvDefaultPreference: 'medium'

debian: '10'
freifunk_karte_api: 'false'

nodelist: 'true'

block_rfc1918_interface: "{{ wan_base_interface }}"
