---

- name: Copy vimrc configuration to root
  copy:
    src: 'files/home_enviroment/vimrc'
    dest: '/root/.vimrc'
    owner: 'root'
    group: 'root'
    mode: 'u=rw,g=r,o=r'

- name: Copy vimrc to users
  copy:
    src: 'files/home_enviroment/vimrc'
    dest: '/home/{{ item }}/.vimrc'
    owner: '{{ item }}'
    group: 'admins'
    mode: 'u=rw,g=r,o=r'
  with_items: '{{ admins }}'

- name: Copy bashrc configuration to users
  copy:
    src: 'files/home_enviroment/bashrc'
    dest: '/home/{{ item }}/.bashrc'
    owner: '{{ item }}'
    group: 'admins'
    mode: 'u=rw,g=r,o=r'
  with_items: '{{ admins }}'


- name: Create a global bashrc
  copy:
    src: 'files/home_enviroment/bash.bashrc'
    dest: '/etc/bash.bashrc'
    owner: 'root'
    group: 'root'
    mode: 'u=rw,g=r,o=r'

- name: Set fancy motd
  script: 'files/home_enviroment/motd.sh {{ hostname }}'

