---
- name: Create www-data group
  group:
    name: 'www-data'
    state: present

- name: Create www-data user
  user:
    name: 'www-data'
    group: 'www-data'
    shell: '/bin/false'
    system: yes
    createhome: no

- name: Create '/var/www/HOSTNAME' directory
  file:
    path: '/var/www/{{ hostname }}'
    state: directory
    mode: 'u=rwx,g=rx,o=rx'


- name: Create '/var/www/HOSTNAME/assets' directory
  file:
    path: '/var/www/{{ hostname }}/assets'
    state: directory
    mode: 'u=rwx,g=rx,o=rx'


- name: Create '/var/www/HOSTNAME/images' directory
  file:
    path: '/var/www/{{ hostname }}/images'
    state: directory
    mode: 'u=rwx,g=rx,o=rx'

- name: Create '/var/www/HOSTNAME/assets/js' directory
  file:
    path: '/var/www/{{ hostname }}/assets/js'
    state: directory
    mode: 'u=rwx,g=rx,o=rx'


- name: Create '/var/www/HOSTNAME/assets/fonts' directory
  file:
    path: '/var/www/{{ hostname }}/assets/fonts'
    state: directory
    mode: 'u=rwx,g=rx,o=rx'


- name: Create '/var/www/HOSTNAME/assets/css' directory
  file:
    path: '/var/www/{{ hostname }}/assets/css'
    state: directory
    mode: 'u=rwx,g=rx,o=rx'


- name: Create '/var/www/HOSTNAME/assets/js/ie' directory
  file:
    path: '/var/www/{{ hostname }}/assets/js/ie'
    state: directory
    mode: 'u=rwx,g=rx,o=rx'


- name: Standard HTML Page
  template:
    src: 'templates/gateway-page/index.html'
    dest: '/var/www/{{ hostname }}/index.html'
    owner: 'www-data'
    group: 'www-data'
    mode: '0755'

- name: Copy HTML Page
  copy: src={{ item.src }} dest={{ item.dest }} owner='www-data' group='www-data' mode='0755'
  with_items:
    - { src: "templates/gateway-page/images/bg01.jpg", dest: "/var/www/{{ hostname }}/images/bg01.jpg" }
    - { src: "templates/gateway-page/images/bg02.jpg", dest: "/var/www/{{ hostname }}/images/bg02.jpg" }
    - { src: "templates/gateway-page/images/bg03.jpg", dest: "/var/www/{{ hostname }}/images/bg03.jpg" }
    - { src: "templates/gateway-page/images/bg04.jpg", dest: "/var/www/{{ hostname }}/images/bg04.jpg" }
    - { src: "templates/gateway-page/assets/css/main.css", dest: "/var/www/{{ hostname }}/assets/css/main.css" }
    - { src: "templates/gateway-page/assets/css/font-awesome.min.css", dest: "/var/www/{{ hostname }}/assets/css/font-awesome.min.css" }
    - { src: "templates/gateway-page/assets/css/ie8.css", dest: "/var/www/{{ hostname }}/assets/css/ie8.css" }
    - { src: "templates/gateway-page/assets/css/ie9.css", dest: "/var/www/{{ hostname }}/assets/css/ie9.css" }
    - { src: "templates/gateway-page/assets/fonts/FontAwesome.otf", dest: "/var/www/{{ hostname }}/assets/fonts/FontAwesome.otf" }
    - { src: "templates/gateway-page/assets/fonts/fontawesome-webfont.eot", dest: "/var/www/{{ hostname }}/assets/fonts/fontawesome-webfont.eot" }
    - { src: "templates/gateway-page/assets/fonts/fontawesome-webfont.svg", dest: "/var/www/{{ hostname }}/assets/fonts/fontawesome-webfont.svg" }
    - { src: "templates/gateway-page/assets/fonts/fontawesome-webfont.ttf", dest: "/var/www/{{ hostname }}/assets/fonts/fontawesome-webfont.ttf" }
    - { src: "templates/gateway-page/assets/fonts/fontawesome-webfont.woff", dest: "/var/www/{{ hostname }}/assets/fonts/fontawesome-webfont.woff" }
    - { src: "templates/gateway-page/assets/fonts/fontawesome-webfont.woff2", dest: "/var/www/{{ hostname }}/assets/fonts/fontawesome-webfont.woff2" }
    - { src: "templates/gateway-page/assets/js/main.js", dest: "/var/www/{{ hostname }}/assets/js/main.js" }
    - { src: "templates/gateway-page/assets/js/ie/html5shiv.js", dest: "/var/www/{{ hostname }}/assets/js/ie/html5shiv.js" }
    - { src: "templates/gateway-page/assets/js/ie/respond.min.js", dest: "/var/www/{{ hostname }}/assets/js/ie/respond.min.js" }


