---

- name: Install some dependencies
  apt:
    pkg: '{{ item }}'
    state: 'latest'
    update_cache: yes
    cache_valid_time: 86400
  with_items:
    - zip
    - git
    - flex
    - bison
    - pkg-config
    - libnacl-dev
    - libcap-dev
    - libjson-c-dev
    - cmake-curses-gui

- name: Download libsodium
  get_url:
    url: 'https://github.com/jedisct1/libsodium/releases/download/{{ fastd_libsodium_version }}/libsodium-{{ fastd_libsodium_version }}.tar.gz'
    dest: '/tmp/fastd_libsodium.tar.gz'
    checksum: sha256:{{ fastd_libsodium_sha256sum }}

- name: Create '/tmp/fastd_libsodium/' Directory
  file:
    path: '/tmp/fastd_libsodium'
    state: directory
    mode: 'u=rwx,g=rx,o=rx'

- name: Unpack libsodium archive
  unarchive:
    src: '/tmp/fastd_libsodium.tar.gz'
    dest: '/tmp/fastd_libsodium/'
    remote_src: yes

- name: Configure libsodium
  shell: '/tmp/fastd_libsodium/libsodium-{{ fastd_libsodium_version }}/configure'
  args:
    chdir: '/tmp/fastd_libsodium/libsodium-{{ fastd_libsodium_version }}'

- name: Make libsodium
  make:
    chdir: '/tmp/fastd_libsodium/libsodium-{{ fastd_libsodium_version }}'
    params:
      NUM_THREADS: 4

- name: Make install libsodium
  make:
    chdir: '/tmp/fastd_libsodium/libsodium-{{ fastd_libsodium_version }}'
    target: install
    params:
      NUM_THREADS: 4

- name: Execute ldconfig
  shell: ldconfig

- name: Download libuecc
  get_url:
    url: 'https://projects.universe-factory.net/attachments/download/85'
    dest: '/tmp/libuecc-7.tar.xz'
    checksum: sha256:b94aef08eab5359d0facaa7ead2ce81b193eef0c61379d9835213ebc0a46257a

- name: Create '/tmp/libuecc/' Directory
  file:
    path: '/tmp/libuecc'
    state: directory
    mode: 'u=rwx,g=rx,o=rx'

- name: Create '/tmp/libuecc/build' Directory
  file:
    path: '/tmp/libuecc/build'
    state: directory
    mode: 'u=rwx,g=rx,o=rx'

- name: Unpack libuecc archive
  unarchive:
    src: '/tmp/libuecc-7.tar.xz'
    dest: '/tmp/libuecc/'
    remote_src: yes

- name: Cmake libuecc
  shell: 'cmake /tmp/libuecc/libuecc-7'
  args:
    chdir: '/tmp/libuecc/build'

- name: Make libuecc
  make:
    chdir: '/tmp/libuecc/build'
    params:
      NUM_THREADS: 4

- name: Make install libuecc
  make:
    chdir: '/tmp/libuecc/build'
    target: install
    params:
      NUM_THREADS: 4

- name: Execute ldconfig
  shell: ldconfig

- name: Download fastd
  get_url:
    #url: 'https://projects.universe-factory.net/attachments/download/86'
    #checksum: sha256:714ff09d7bd75f79783f744f6f8c5af2fe456c8cf876feaa704c205a73e043c9
    url: 'https://git.universe-factory.net/fastd/snapshot/fastd-18.tar'
    checksum: sha256:dce99ee057f43e3d732a120fb0cb60acb3b86e8231d3dd64ab72fc1254c2491a
    dest: '/tmp/fastd-18.tar'

- name: Create '/tmp/fastd' Directory
  file:
    path: '/tmp/fastd'
    state: directory
    mode: 'u=rwx,g=rx,o=rx'

- name: Create '/tmp/fastd/build' Directory
  file:
    path: '/tmp/fastd/build'
    state: directory
    mode: 'u=rwx,g=rx,o=rx'

- name: Unpack fastd archive
  unarchive:
    src: '/tmp/fastd-18.tar'
    dest: '/tmp/fastd/'
    remote_src: yes

- name: Cmake fastd
  shell: 'cmake /tmp/fastd/fastd-18'
  args:
    chdir: '/tmp/fastd/build'

- name: Make fastd
  make:
    chdir: '/tmp/fastd/build'
    params:
      NUM_THREADS: 4

- name: Make install fastd
  make:
    chdir: '/tmp/fastd/build'
    target: install
    params:
      NUM_THREADS: 4
